name: MacOSX BigSur MetaCall build
on: [push]
jobs:
  build-action:
    runs-on: macos-latest
    steps:
      - name: Building MetaCall on MacOS BigSur
        uses: actions/checkout@v3
      - run: | 
          chmod +x ./build.sh
          ./build.sh
      - name: Upload build tarball production artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: metacall-tarball
          path: metacall-tarball-macos-x64.zip
          if-no-files-found: error
  python-tests:
    name: Python loader tests
    needs: build-action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-12]
    steps:
      - name: Download build/artifact from cache
        uses: actions/download-artifact@v3
        with:
          name: metacall-tarball
          path: tarball
      - run: | 
          unzip -l tarball/metacall-tarball-macos-x64.zip
          cp metacall-tarball-macos-x64.zip /tmp/
          cd /tmp && unzip "./metacall-tarball-macos-x64.zip"
          echo "print(\"Hello World from Python GitHub Actions\")" > /tmp/py-eval-test.py
          chmod +x /tmp/metacall.sh
          /tmp/metacall/metacallcli.app/Contents/MacOS/metacallcli /tmp/py-eval-test.py
          /tmp/metacall.sh /tmp/py-eval-test.py
