name: MacOSX bigsur MetaCall build
on: [push]
jobs:
  build-action:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build.sh
      - run: tar -cvf metacall-tarball-macos-x64.zip
