name: MacOSX BigSur MetaCall build
on: [push]
jobs:
  build-action:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./build.sh
      - run: ./build.sh
      - run: unzip -l ./metacall-tarball-macos-x64.zip
