name: MacOSX Python loader test
on: [push]
jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-12]
    steps:
      - name: Download build/artifact from cache
        uses: actions/download-artifact@v3
        with:
          name: metacall-tarball
      - run: unzip -l ./metacall-tarball-macos-x64.zip
      - run: cd /tmp && unzip "/Users/runner/work/distributable-macos/distributable-macos/metacall-tarball-macos-x64.zip"
      - run: echo "print(\"Hello World from Python GitHub Actions\")" > /tmp/py-eval-test.py
      - run: chmod +x /tmp/metacall.sh
      - run: /tmp/metacall/metacallcli.app/Contents/MacOS/metacallcli /tmp/py-eval-test.py
      - run: /tmp/metacall.sh /tmp/py-eval-test.py
